name: Lint
on:
  pull_request:
    branches: [main]
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    container: node:18
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      # - run: npm ci
      # - run: node api-tests/migrate.js
      #   env:
      #     DATABASE_URL: postgres://postgres:postgres@postgres
      - run: npm run lint
      # - run: npm run test
      #   env:
      #     DATABASE_URL: postgres://postgres:postgres@postgres
